[network]
name = "devnet"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw"
balance = 10_000_000_000_000

[accounts.wallet_1]
mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt jealous season lumber machine catalog harbor moon jeans alarm maple siren blade"
balance = 10_000_000_000_000

[accounts.wallet_2]
mnemonic = "hold excess usual excess ring elephant install account pilot effort island intact blossom trade essence battle march fatal roof gold gaze sauce sweet plunge"
balance = 10_000_000_000_000

[accounts.wallet_3]
mnemonic = "cycle puppy glare enroll cost improve round trend wrist mushroom scorpion tower proud admit age agent proof stay combine note hub primary stomach kiss"
balance = 10_000_000_000_000

[devnet]
disable_stacks_explorer = false
disable_stacks_api = false
stacks_node_wait_time_for_microblocks = 50
